/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * demo api server
 * demo api
 * OpenAPI spec version: 1.0
 */

export interface DummyModel01 {
  value1: string;
  value2: number;
}
