/**
 * Generated by orval v6.14.4 🍺
 * Do not edit manually.
 * demo api server
 * demo api
 * OpenAPI spec version: 1.0
 */
import { rest } from 'msw';
import { faker } from '@faker-js/faker';

export const getDummyControllerGetTestMock = () => ({
  value1: faker.random.word(),
  value2: faker.datatype.number({ min: undefined, max: undefined }),
});

export const getDefaultMSW = () => [
  rest.get('*/api', (_req, res, ctx) => {
    return res(ctx.delay(1000), ctx.status(200, 'Mocked status'));
  }),
  rest.get('*/api/dummy/get-test', (_req, res, ctx) => {
    return res(
      ctx.delay(1000),
      ctx.status(200, 'Mocked status'),
      ctx.json(getDummyControllerGetTestMock())
    );
  }),
];
